### ISSUE TITLE
Consistent naming for Operation/Ability

### ISSUE THREAD

**Issue by andrewzhurov** [ucan-wg/invocation#26]
In the UCAN spec a verb to call on a resource is [called `Ability`](https://github.com/ucan-wg/spec#25-capability), whereas in invocation spec it's denoted as `Operation`.
Would it be more consistent to use the same name across specs?
Consistency would spare some cognitive effort to keep in mind Operation = Ability, make learning the specs a bit easier, as "ah, that's a familiar concept" will click faster.

**Comment by expede** [comment]
Yep good point! Will fix 👍 Thanks
